// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../test/js/main.js', ['main'], ['goog.dom', 'module'], false);
goog.addDependency('../../../../test/js/module.jsx', ['module'], ['goog.dom.classlist'], false);
